goldencobra_events:
    active_admin:
      menue:
        panels:
          display: "false"
        invoices:
          display: "true"
        sponsors:
          display: "true"
        artists:
          display: "true"
    agb_article_id: "0"
    event_pricegroup:
        available:
            default: "false"
    ticket:
        last_ticket_number: "0"
        logo_for_ticket: "logo.png"
        veranstalter: "Eine Veranstaltung von Verlag der Tagesspiegel GmbH."
        sponsorenleiste_for_ticket: "leiste.png"
    invoice:
        last_invoice_number: "0"
        event_name_for_invoice: "DK"
    printer:
        email: 'test@test.de'
    send_with_pixelletter:
        value: 'true'
        type: 'boolean'
    pixelletter_testmodus:
        value: 'true'
        type: 'boolean'
    event:
        title_for_email: 'Tagesspiegel Veranstaltung'
        event_title_for_email_body: 'Tagesspiegel-Event 2012'
        cancellation:
            info_email: "foo@bar.baz"
        registration_basket:
            headline: "Sie haben gewählt:"
            greeting: "Hallo "
            submit_text: "Anmeldung abschließen"
            remove_text: "entfernen"
            description: "Bitte füllen Sie noch Ihre Benutzerdaten aus..."
            completed: "Anmeldung abgeschlossen"
        article_events:
            register_text: "Für diese Veranstaltung anmelden"
        registration:
            mailer:
                from: "cloudforum@ikusei.de"
                subject: "Anmeldebestaetigung Cloud Forum 2012"
                reply_to: "cloudforum@tagesspiegel.de"
            price_informations: "Der Preis beinhaltet bestimmte Sachen."
            child_registration_informations: "Ich melde mich für folgende Unterevents an:"
            enter_user_data: "Mit Anmeldung fortfahren"
            choose_event: "Auswaehlen"
            exclusive_description: "Bitte wählen Sie zwischen einer dieser Optionen"
            webcode:
                title: "Gutschein-Code eingeben"
                description: "Sofern Sie einen Webcode besitzen, geben Sie diesen hier bitte an."
                submit: "Absenden"
            completed: "Ihre Registrierung wurde erfolgreich abgeschlossen! Sie erhalten zusätzliche eine Email"
            added:
                headline: "Dieser Event wurde zu Ihrer Buchungsliste hinzugefügt"
            to_add:
                headline: "Bitte wählen Sie die passende Preisgruppe:"
                submit: "Weiter"
                submit_disabled: "Anfrage wird übermittelt ..."
            errors:
                no_events_selected: "Es wurden noch keine Event gewählt"
                no_user_selected: "Bitte füllen Sie Ihre Benutzerdaten aus"
                user_not_exists: "Diesen Benutzer gibt es nicht"
                no_price_groups_defined: "Es wurden für diesen Event keine Preisgruppen angelegt"
            user_form:
                title_summary: "Anmeldung Cloud Forum am 26. und 27. April 2012 in Berlin"
                headline: "Bitte füllen Sie Ihre Benutzerdaten aus"
                sub_headline: "Personeninformationen und Firmendaten"
                description: "wir behandeln Ihre Daten vertraulich und nutzen diese nur im für diese Veranstaltung"
                footer_description: "Die Rechnung wird Ihnen durch den technischen Dienstleister des Tagesspiegels, die ikusei GmbH, übersendet."
                account_description: "Bitte wählen Sie ein Passwort (mit diesem können Sie Ihre Bestellung später noch anpassen)"
                user_fieldset_name: "Angaben zu Ihrer Person"
                user_info_fieldset_name: "Detailinformationen"
                company_fieldset_name: "Angaben zu Ihrer Firma"
                account_fieldset_name: "Accountdaten"
                company_adress_fieldset_name: "Adresse"
                alternate_billing_address: "Abweichende Rechnungsadresse?"
                next_step_label: "weiter ..."
                submit: "Verbindlich bestellen"
                final_submit: "Verbindlich bestellen"
                submit_disabled: "Anfrage wird übermittelt ..."
                teilnahmebedingungen1: "Der Teilnahmebetrag für diese Veranstaltung inklusive Mittagessen, Dinner-Veranstaltung am 26. April und Pausengetränken pro Person zzgl. MwSt ist nach Erhalt der Rechnung fällig. Nach Eingang Ihrer Anmeldung erhalten Sie eine Bestätigung."
                teilnahmebedingungen2: "Die Stornierung (nur schriftlich) ist bis 14 Tage vor Veranstaltungsbeginn kostenlos möglich, danach wird die Hälfte des Teilnahmebetrags erhoben. Bei Nichterscheinen oder Stornierung am Veranstaltungstag wird der gesamte Teilnahmebetrag fällig."
                teilnahmebedingungen3: "Gerne akzeptieren wir ohne zusätzliche Kosten einen Ersatzteilnehmer. Programmänderungen aus dringendem Anlass behält sich der Veranstalter vor."
                newsletter: "Newsletter"
                agb: "AGB"
                errors:
                    firstname: "Vorname muss ausgefüllt sein"
                    lastname: "Nachname muss ausgefüllt sein"
                    email: "Email muss ausgefüllt sein"
                    phone: "Telefon muss ausgefüllt sein"
                    fax: "Faxnummer muss ausgefüllt sein"
                    company_title: "Firmenname muss ausgefüllt sein"
                    company_street: "Strasse muss ausgefüllt sein"
                    company_city: "Stadt muss ausgefüllt sein"
                    company_zip: "PLZ muss ausgefüllt sein"
                    company_country: "Land muss ausgefüllt sein"
                    password: "Das Passwort muss mindestens aus 6 Zeichen bestehen"
                    password_confirmation: "Passwort und die Wiederholung müssen übereinstimmen"
                    agb: "Die AGBs müssen akzeptiert werden"
                user_label:
                    gender: "Anrede"
                    gender_male: "Herr"
                    gender_female: "Frau"
                    title: "Titel"
                    firstname: "Vorname"
                    lastname: "Nachname"
                    function: "Function"
                    email: "Email"
                    phone: "Telefon"
                    fax: "Fax"
                    googleplus: "Google+"
                    xing: "Xing"
                    linkedin: "LinkedIn"
                    twitter: "Twitter"
                    facebook: "Facebook"
                    billing_gender: "Anrede"
                    billing_department: "Abteilung/Kostenstelle"
                    billing_street: "Straße oder Postfach"
                    billing_firstname: "Vorname"
                    billing_lastname: "Nachname"
                company_label:
                    title: "Unternehmen"
                    legal_form: "Rechtsform"
                    phone: "Telefon"
                    fax: "Fax"
                    homepage: "Homepage"
                    street: "Strasse"
                    zip: "PLZ"
                    city: "Ort"
                    region: "Bezirk"
                    country: "Land"
                    sector: "Branche"
                    billing_title: "Firma"
                account_label:
                    password: "Passwort"
                    confirm_password: "Passwort wiederholen"
    imap:
        domain: "my.server.com"
        login: "my-username"
        password: "my-password"
        use_blacklist: "false"
        bounce_recipient: "bounce-recipient@goldencobra.com"
        send_bounce_report: 'false'
        bouncer_mailer:
            from: 'do-not-reply@goldencobra.com'
            subject: 'Bounce report'
            reply_to: ''
