goldencobra_events:
    event:
        registration_basket:
            headline: "Sie haben gewählt:"
            submit_text: "Anmeldung abschließen"
            remove_text: "entfernen"    
            description: "Um Ihre Reservierung abzuschließen, bitte hier klicken..."    
        article_events:
            register_text: "Anmelden"
        registration:
            added:
                headline: "Dieser Event wurde zu Ihrer Buchungsliste hinzugefügt"
            to_add:
                headline: "Dieser Event besitzt mehrere Preisgruppen zur Auswahl"
                submit: "Auswahl übernehmen"
            errors:
                no_events_selected: "Es wurden noch keine Event gewählt"            
                no_user_selected: "Bitte füllen Sie Ihre Benutzerdaten aus"
                user_not_exists: "Diesen Benutzer gibt es nicht"
                no_price_groups_defined: "Es wurden für diesen Event keine Preisgruppen angelegt"
            user_form:
                headline: "Bitte füllen Sie Ihre Benutzerdaten aus"
                description: "wir behandeln Ihre Daten vertraulich und nutzen diese nur im für diese Veranstaltung"
                submit: "Absenden"