goldencobra_events:
    event:
        registration_basket:
            headline: "Sie haben gewählt:"
            greeting: "Hallo "
            submit_text: "Anmeldung abschließen"
            remove_text: "entfernen"    
            description: "Bitte füllen Sie noch Ihre Benutzerdaten aus..."    
            completed: "Anmeldung abgeschlossen"
        article_events:
            register_text: "Anmelden"
        registration:
            enter_user_data: "Mit Anmeldung fortfahren"
            exclusive_description: "Bitte wählen Sie zwischen einer dieser Optionen"
            webcode:
                title: "Webcode eingeben"
                description: "Sofern Sie einen Webcode besitzen, geben Sie diesen hier bitte an."
                submit: "absenden"
            completed: "Ihre Registrierung wurde erfolgreich abgeschlossen! Sie erhalten zusätzliche eine Email"
            added:
                headline: "Dieser Event wurde zu Ihrer Buchungsliste hinzugefügt"
            to_add:
                headline: "Dieser Event besitzt mehrere Preisgruppen zur Auswahl"
                submit: "Auswahl übernehmen"
            errors:
                no_events_selected: "Es wurden noch keine Event gewählt"            
                no_user_selected: "Bitte füllen Sie Ihre Benutzerdaten aus"
                user_not_exists: "Diesen Benutzer gibt es nicht"
                no_price_groups_defined: "Es wurden für diesen Event keine Preisgruppen angelegt"
            user_form:
                headline: "Bitte füllen Sie Ihre Benutzerdaten aus"
                sub_headline: "Personeninformationen und Firmendaten"
                description: "wir behandeln Ihre Daten vertraulich und nutzen diese nur im für diese Veranstaltung"
                account_description: "Melden Sie sich später mit Ihrer Email und folgendem Passwort an:"
                user_fieldset_name: "Benutzerdaten"
                user_info_fieldset_name: "Detailinformationen"
                company_fieldset_name: "Firmendaten"
                account_fieldset_name: "Accountdaten"
                company_adress_fieldset_name: "Adresse"
                next_step_label: "weiter ..."
                submit: "Absenden"
                errors:
                    firstname: "Vorname muss ausgefüllt sein"
                    lastname: "Nachname muss ausgefüllt sein"
                    email: "Email muss ausgefüllt sein"
                    phone: "Telefon muss ausgefüllt sein"
                    fax: "Faxnummer muss ausgefüllt sein"
                    company_title: "Firmenname muss ausgefüllt sein"
                    company_street: "Strasse muss ausgefüllt sein"
                    company_city: "Stadt muss ausgefüllt sein"
                    company_zip: "PLZ muss ausgefüllt sein"                                                            
                    company_country: "Land muss ausgefüllt sein"      
                    password: "Das Passwort muss mindestens aus 6 Zeichen bestehen"
                    password_confirmation: "Passwort und die Wiederholung müssen übereinstimmen"
                user_label:
                    gender: "Anrede"
                    gender_male: "Herr"
                    gender_female: "Frau"
                    title: "Titel"
                    firstname: "Vorname"
                    lastname: "Nachname"
                    function: "Function"
                    email: "Email"
                    phone: "Telefon"
                    fax: "Fax"
                    googleplus: "Google+"
                    xing: "Xing"
                    linkedin: "LinkedIn"
                    twitter: "Twitter"
                    facebook: "Facebook"
                company_label:
                    title: "Name"
                    legal_form: "Rechtsform"
                    phone: "Telefon"
                    fax: "Fax"
                    homepage: "Homepage"
                    street: "Strasse"
                    zip: "Postleitzahl"
                    city: "Ort"
                    region: "Bezirk"
                    country: "Land"
                    sector: "Branche"
                account_label:
                    password: "Passwort"
                    confirm_password: "Passwort wiederholen"
                    
                    

                
                      
